#    ░█░█░▀█▀░▀█▀░▀█▀░█░█                                
#    ░█▀▄░░█░░░█░░░█░░░█░                                
#    ░▀░▀░▀▀▀░░▀░░░▀░░░▀░                                
# 
#    ░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀                            
#    ░█░░░█░█░█░░░█░█░█▀▄░▀▀█                            
#    ░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀                            
#                     
#    ░█░█░█▀█░▀▀█░█▀█░█░█░█░█░█▀▄░█▀█░░░█░█░▀█▀░█▀▄░█░█
#    ░░█░░█░█░▄▀░░█▀█░█▀▄░█░█░█▀▄░█▀█░░░█▀█░░█░░█▀▄░█░█
#    ░░▀░░▀▀▀░▀▀▀░▀░▀░▀░▀░▀▀▀░▀░▀░▀░▀░░░▀░▀░▀▀▀░▀░▀░▀▀▀
#---------------------------------------------------------

foreground               #2a1848
background               #f0e8f5
selection_foreground     none
selection_background     none

cursor                   none
cursor_text_color        #2a1848

url_color                #2878a8

active_tab_foreground    #ead8f2
active_tab_background    #a02868
inactive_tab_foreground  #4e3e6e
inactive_tab_background  #ead8f2
tab_bar_background       none

active_border_color      #4840b0
inactive_border_color    #c0b0d8

# black
color0   #d4c4e0
color8   #7868a0

# red
color1   #983040
color9   #a02868

# green
color2   #187870
color10  #287848

# yellow
color3   #985818
color11  #887018

# blue
color4   #2858b8
color12  #2878a8

# magenta
color5   #8830a0
color13  #a03868

# cyan
color6   #286890
color14  #4840b0

# white
color7   #4e3e6e
color15  #2a1848
