#    ░█░█░▀█▀░▀█▀░▀█▀░█░█                                
#    ░█▀▄░░█░░░█░░░█░░░█░                                
#    ░▀░▀░▀▀▀░░▀░░░▀░░░▀░                                
# 
#    ░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀                            
#    ░█░░░█░█░█░░░█░█░█▀▄░▀▀█                            
#    ░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀                            
#                     
#    ░█░█░█▀█░▀▀█░█▀█░█░█░█░█░█▀▄░█▀█░░░█░█░█▀█░█▀▄░█░█
#    ░░█░░█░█░▄▀░░█▀█░█▀▄░█░█░█▀▄░█▀█░░░░█░░█░█░█▀▄░█░█
#    ░░▀░░▀▀▀░▀▀▀░▀░▀░▀░▀░▀▀▀░▀░▀░▀░▀░░░░▀░░▀▀▀░▀░▀░▀▀▀
#---------------------------------------------------------

foreground               #d0daf0
background               #2a3450
selection_foreground     none
selection_background     none

cursor                   none
cursor_text_color        #d0daf0

url_color                #7ab0c8

active_tab_foreground    #e8eef8
active_tab_background    #e098a0
inactive_tab_foreground  #b0bcd8
inactive_tab_background  #303c5c
tab_bar_background       none

active_border_color      #8898c8
inactive_border_color    #6070a0

# black
color0   #18203a
color8   #9098c0

# red
color1   #c07888
color9   #e098a0

# green
color2   #609098
color10  #7aa898

# yellow
color3   #d0a870
color11  #e8d870

# blue
color4   #6080b8
color12  #7ab0c8

# magenta
color5   #b898d0
color13  #d8aac4

# cyan
color6   #507098
color14  #8898c8

# white
color7   #b0bcd8
color15  #e8eef8